-- 【中文：每日打卡（H2 版本）—— 每个用户每天最多一条，记录连续天数与发放的经验/金币奖励快照。
--   连续打卡 streak 越长，经验倍率与金币越高。结构与 mysql 版本保持一致。】
-- Daily check-in: one row per user per day, tracks streak + rewards.
CREATE TABLE daily_checkin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 【中文：主键，H2 自增 ID】
    user_id BIGINT NOT NULL,                                  -- 【中文：关联用户 ID】
    checkin_date DATE NOT NULL,                               -- 【中文：打卡日期】
    streak INT NOT NULL,                                      -- 【中文：连续打卡天数（含当天）】
    exp_reward INT NOT NULL,                                  -- 【中文：当天经验奖励快照】
    coin_reward INT NOT NULL,                                 -- 【中文：当天金币奖励快照】
    created_at TIMESTAMP(6) NOT NULL,                         -- 【中文：创建时间】
    CONSTRAINT fk_daily_checkin_user FOREIGN KEY (user_id) REFERENCES user_account(id),
    CONSTRAINT uq_daily_checkin_user_date UNIQUE (user_id, checkin_date)
);
CREATE INDEX idx_daily_checkin_user ON daily_checkin(user_id);
