-- 【中文：宠物市场（H2 版本）—— 移除「默认宠物」一对一模型，改为「品种目录 + 用户拥有多只」。
--   非破坏式：保留旧 pet 表不动，新建 owned_pet 并把现有宠物迁移过去（active=true，默认品种 feixue）。
--   每只宠物独立保有等级/经验/心情，互不共享；active=true 为出战宠物。结构与 mysql 版本一致。】
-- Pet market: species catalog + per-user owned pets (non-destructive; old pet table left intact).

CREATE TABLE pet_species (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 【中文：主键】
    slug VARCHAR(64) NOT NULL UNIQUE,                         -- 【中文：唯一标识】
    name VARCHAR(64) NOT NULL,                                -- 【中文：展示名】
    rarity VARCHAR(32),                                       -- 【中文：稀有度 COMMON/RARE/EPIC】
    price INT NOT NULL,                                       -- 【中文：金币价格，0=免费】
    starter BOOLEAN NOT NULL,                                 -- 【中文：是否入门款（可免费领养首只）】
    sprite_path VARCHAR(255),                                 -- 【中文：前端 spritesheet 路径】
    description VARCHAR(255),                                 -- 【中文：简介】
    sort_order INT NOT NULL                                   -- 【中文：展示排序】
);

-- 上架品种（多品种暂复用同一张占位 spritesheet，后续可用 hatch 技能逐一替换为专属形象）
INSERT INTO pet_species (id, slug, name, rarity, price, starter, sprite_path, description, sort_order) VALUES
 (1, 'feixue', '飞雪', 'COMMON', 0,   TRUE,  '/pets/feixue/spritesheet.webp', '冷静专注的入门小伙伴', 1),
 (2, 'mochi',  '麻糬', 'COMMON', 0,   TRUE,  '/pets/feixue/spritesheet.webp', '软糯黏人的入门小伙伴', 2),
 (3, 'ember',  '炭炭', 'RARE',   120, FALSE, '/pets/feixue/spritesheet.webp', '热情似火，督促你别拖延', 3),
 (4, 'aurora', '极光', 'EPIC',   300, FALSE, '/pets/feixue/spritesheet.webp', '稀有梦幻，陪你冲刺高目标', 4);

CREATE TABLE owned_pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- 【中文：主键】
    user_id BIGINT NOT NULL,                                  -- 【中文：所属用户】
    species_id BIGINT,                                        -- 【中文：品种】
    name VARCHAR(255),                                        -- 【中文：宠物名】
    avatar_url VARCHAR(255),                                  -- 【中文：自定义头像】
    level INT,                                                -- 【中文：等级】
    current_exp INT,                                          -- 【中文：当前经验】
    next_level_exp INT,                                       -- 【中文：升级所需经验】
    mood INT,                                                 -- 【中文：心情 0-100】
    satiety INT,                                              -- 【中文：饱腹感 0-100】
    growth_stage VARCHAR(32),                                 -- 【中文：成长阶段】
    status VARCHAR(32),                                       -- 【中文：状态】
    active BOOLEAN NOT NULL DEFAULT TRUE,                     -- 【中文：是否出战】
    acquired_at TIMESTAMP(6),                                 -- 【中文：获得时间】
    created_at TIMESTAMP(6),                                  -- 【中文：创建时间】
    updated_at TIMESTAMP(6),                                  -- 【中文：更新时间】
    CONSTRAINT fk_owned_pet_user FOREIGN KEY (user_id) REFERENCES user_account(id),
    CONSTRAINT fk_owned_pet_species FOREIGN KEY (species_id) REFERENCES pet_species(id)
);
CREATE INDEX idx_owned_pet_user ON owned_pet(user_id);
CREATE INDEX idx_owned_pet_user_active ON owned_pet(user_id, active);

-- 迁移现有宠物 → owned_pet（每个老用户的宠物保留为出战，赋默认品种 feixue）
INSERT INTO owned_pet (user_id, species_id, name, avatar_url, level, current_exp, next_level_exp, mood, satiety, growth_stage, status, active, acquired_at, created_at, updated_at)
SELECT user_id, 1, name, avatar_url, level, current_exp, next_level_exp, mood, satiety, growth_stage, status, TRUE, created_at, created_at, updated_at
FROM pet;
