-- 【中文：共享自习室（H2 版本）—— study_room 房间 + room_member 成员（含在线心跳/专注状态）。
--   在线靠 last_seen_at 在窗口内判定；轻量在线状态，不做实时聊天/音视频。结构与 mysql 版本一致。】
-- Shared study rooms: rooms + members with heartbeat presence.
CREATE TABLE study_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 【中文：主键】
    name VARCHAR(64) NOT NULL,                                -- 【中文：房间名】
    owner_id BIGINT NOT NULL,                                 -- 【中文：创建者】
    created_at TIMESTAMP(6) NOT NULL,                         -- 【中文：创建时间】
    CONSTRAINT fk_study_room_owner FOREIGN KEY (owner_id) REFERENCES user_account(id)
);
CREATE INDEX idx_study_room_created ON study_room(created_at);

CREATE TABLE room_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 【中文：主键】
    room_id BIGINT NOT NULL,                                  -- 【中文：房间】
    user_id BIGINT NOT NULL,                                  -- 【中文：成员用户】
    joined_at TIMESTAMP(6) NOT NULL,                          -- 【中文：加入时间】
    last_seen_at TIMESTAMP(6) NOT NULL,                       -- 【中文：最近心跳（判在线）】
    focusing BOOLEAN NOT NULL DEFAULT FALSE,                  -- 【中文：当前是否在专注】
    focus_seconds INT NOT NULL DEFAULT 0,                     -- 【中文：累计专注秒数】
    CONSTRAINT fk_room_member_room FOREIGN KEY (room_id) REFERENCES study_room(id),
    CONSTRAINT fk_room_member_user FOREIGN KEY (user_id) REFERENCES user_account(id),
    CONSTRAINT uq_room_member UNIQUE (room_id, user_id)
);
CREATE INDEX idx_room_member_room ON room_member(room_id);
CREATE INDEX idx_room_member_user ON room_member(user_id);
