-- 【中文：基线迁移脚本（H2 版本）—— 由 JPA 实体自动生成，包含 Soulous 系统全部核心表的建表语句。
--   与 MySQL 版本结构一致，但使用 H2 语法（如 GENERATED BY DEFAULT AS IDENTITY、TIMESTAMP(6)、BOOLEAN 等）。
--   用于本地开发和单元测试环境。】
-- Generated by SchemaDumpTool from JPA entities. Do not hand-edit; rerun the tool if entities change.
-- For existing databases: Flyway is configured with baseline-on-migrate=true, baseline-version=1
-- so this script is *skipped* on already-populated databases and only runs on fresh installs.

    -- 【中文：管理员审计日志表 —— 记录管理员对申诉和提交的审核操作（批准/驳回/需补充等），
    --   包含经验值变动、操作结果、操作人信息，用于追溯管理行为。】
    create table admin_audit_log (
        exp_amount integer,
        admin_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        target_id bigint,
        admin_username varchar(64),
        result_status varchar(64),
        comment TEXT,
        action enum ('APPEAL_REVIEW','APPROVE','NEED_MORE','REJECT') not null,
        target_type enum ('APPEAL','SUBMISSION') not null,
        primary key (id)
    );

    -- 【中文：AI 审核表 —— 存储 AI 对任务提交的自动评审结果，包括完整性/质量/相关性各维度评分、
    --   推荐经验值、审核结论（通过/驳回/需人工复核/需补充），以及改进建议。每条提交最多一条 AI 审核记录。】
    create table ai_review (
        completeness_score integer,
        need_manual boolean,
        quality_score integer,
        recommended_exp integer,
        relevance_score integer,
        score integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        submission_id bigint not null unique,
        reason TEXT,
        suggestion TEXT,
        result enum ('MANUAL','NEED_MORE','PASS','REJECT'),
        primary key (id)
    );

    -- 【中文：申诉表 —— 用户对 AI 审核结果不满时可发起申诉，包含申诉理由、截图证据、
    --   管理员审核意见及最终状态（待审核/已批准/已驳回/需补充材料）。关联 task_submission 和 user_account。】
    create table appeal (
        admin_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        reviewed_at timestamp(6),
        submission_id bigint not null,
        user_id bigint not null,
        admin_comment TEXT,
        appeal_reason TEXT,
        screenshot_urls TEXT,
        status enum ('APPROVED','NEED_MORE','PENDING','REJECTED'),
        primary key (id)
    );

    -- 【中文：经验值变动日志表 —— 记录用户每次经验值增减的明细，包括变动数量、
    --   事件类型（任务完成、AI 审核通过等）、变动原因，关联提交和任务用于溯源。】
    create table exp_log (
        exp_amount integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        submission_id bigint,
        task_id bigint,
        user_id bigint not null,
        event_type varchar(255),
        reason varchar(255),
        primary key (id)
    );

    -- 【中文：专注会话表 —— 记录用户的番茄钟/专注计时会话，包含计划时长、已用时长、
    --   开始/结束/暂停时间，状态（运行中/已暂停/已完成/已中止），关联任务和用户。】
    create table focus_session (
        elapsed_seconds integer,
        planned_minutes integer,
        created_at timestamp(6),
        ended_at timestamp(6),
        id bigint generated by default as identity,
        last_started_at timestamp(6),
        started_at timestamp(6),
        task_id bigint,
        user_id bigint not null,
        title varchar(128) not null,
        status enum ('ABORTED','COMPLETED','PAUSED','RUNNING'),
        primary key (id)
    );

    -- 【中文：目标表 —— 用户设定的学习目标，包含标题、目标日期、已完成会话数、
    --   状态（活跃/已达成/已暂停/已放弃/已归档），以及 AI 蒸馏的记忆摘要（JSON 格式）。】
    create table goal (
        session_count integer not null,
        target_date date,
        created_at timestamp(6),
        id bigint generated by default as identity,
        last_session_at timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        title varchar(200) not null,
        distilled_memory_json TEXT,
        status enum ('ABANDONED','ACHIEVED','ACTIVE','ARCHIVED','PAUSED') not null,
        primary key (id)
    );

    -- 【中文：记忆向量嵌入表 —— 存储用户学习记忆的向量表示，用于 RAG 检索增强生成。
    --   包含嵌入内容、向量数据、维度、使用的嵌入模型、来源类型（已完成任务/目标记忆/会话摘要）。】
    create table memory_embedding (
        dimension integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        source_id bigint not null,
        updated_at timestamp(6),
        user_id bigint not null,
        embedded_with varchar(64) not null,
        content TEXT not null,
        vector TEXT not null,
        source_type enum ('COMPLETED_TASK','GOAL_MEMORY','SESSION_SUMMARY') not null,
        primary key (id)
    );

    -- 【中文：内容审核日志表 —— 记录用户输入和 AI 输出的内容安全审核结果，
    --   包含风险评分、审核类别（有害内容/越狱攻击/隐私泄露/提示注入等）、
    --   审核目标（输入/输出）、最终裁定（通过/标记/拦截）。】
    create table moderation_log (
        risk_score integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        session_id bigint,
        user_id bigint,
        context_snippet TEXT,
        evaluated_content TEXT,
        reason TEXT,
        category enum ('CONTEXTUAL_ESCALATION','HARMFUL_CONTENT','JAILBREAK','NONE','OFF_TOPIC_ABUSE','PRIVACY_VIOLATION','PROMPT_INJECTION') not null,
        target enum ('INPUT','OUTPUT') not null,
        verdict enum ('BLOCK','FLAG','PASS') not null,
        primary key (id)
    );

    -- 【中文：宠物表 —— 每个用户拥有一只虚拟宠物，用于 gamification 激励。
    --   包含等级、经验值、心情、饱腹度、成长阶段（蛋/幼年/成年）、状态。】
    create table pet (
        current_exp integer,
        level integer,
        mood integer,
        next_level_exp integer,
        satiety integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null unique,
        avatar_url varchar(255),
        name varchar(255),
        growth_stage enum ('ADULT','CHILD','EGG','GROWING'),
        status enum ('EXCITED','HAPPY','NORMAL','PROUD','REVIEWING','SAD','SLEEPY','WORKING'),
        primary key (id)
    );

    -- 【中文：规划会话表 —— AI 与用户交互的学习规划对话会话，支持新建目标和定期检查两种类型。】
    create table planning_session (
        summarized_up_to_idx integer not null,
        turn_count integer not null,
        ended_at timestamp(6),
        goal_id bigint not null,
        id bigint generated by default as identity,
        last_activity_at timestamp(6),
        started_at timestamp(6),
        user_id bigint not null,
        committed_task_ids_json TEXT,
        pending_plan_json TEXT,
        running_summary TEXT,
        kind enum ('CHECK_IN','NEW_GOAL') not null,
        state enum ('ABANDONED','CLOSED','COMMITMENT','COMMITTED','DRAFTING','PLAN_PROPOSED') not null,
        primary key (id)
    );

    -- 【中文：会话轮次表 —— 存储规划会话中每一轮对话的内容，包含轮次索引、角色和消息内容。】
    create table session_turn (
        idx integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        session_id bigint not null,
        content TEXT,
        role enum ('ASSISTANT','SYSTEM','USER') not null,
        primary key (id)
    );

    -- 【中文：学习记录表 —— 记录用户每次学习的实际情况，包含学习日期、学习时长和摘要。】
    create table study_record (
        record_date date,
        study_minutes integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        task_id bigint,
        user_id bigint not null,
        summary TEXT,
        primary key (id)
    );

    -- 【中文：学习任务表 —— 系统核心表，存储用户创建的各类学习任务，支持多种难度和类型。】
    create table study_task (
        actual_minutes integer,
        base_exp integer,
        deadline date,
        estimated_minutes integer,
        completed_at timestamp(6),
        created_at timestamp(6),
        goal_id bigint,
        id bigint generated by default as identity,
        started_at timestamp(6),
        submitted_at timestamp(6),
        user_id bigint not null,
        title varchar(128) not null,
        course_name varchar(255),
        description TEXT,
        difficulty enum ('CHALLENGE','EASY','HARD','NORMAL'),
        status enum ('AI_APPROVED','AI_REJECTED','APPEALING','COMPLETED','DOING','MANUAL_APPROVED','MANUAL_REJECTED','MODERATION_BLOCKED','NEED_MORE','PAUSED','SUBMITTED','TODO'),
        task_type enum ('CODING','MEMORY','NOTE','REVIEW','SIMPLE','STUDY'),
        primary key (id)
    );

    -- 【中文：任务提交表 —— 用户提交任务完成证明的核心表，支持文字/代码/截图/链接等多种证明方式。】
    create table task_submission (
        study_minutes integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        task_id bigint not null,
        updated_at timestamp(6),
        user_id bigint not null,
        admin_comment TEXT,
        code_snippet TEXT,
        moderation_reason TEXT,
        proof_link varchar(255),
        screenshot_url varchar(255),
        screenshot_urls TEXT,
        submit_type varchar(255),
        text_proof TEXT,
        status enum ('AI_APPROVED','AI_REJECTED','MANUAL_APPROVED','MANUAL_REJECTED','MODERATION_BLOCKED','NEED_MORE','PENDING'),
        primary key (id)
    );

    -- 【中文：用户账户表 —— 系统用户主表，包含用户名、密码、角色等核心信息。】
    create table user_account (
        token_version integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        username varchar(64) not null unique,
        avatar_url varchar(255),
        email varchar(255),
        nickname varchar(255),
        password varchar(255) not null,
        role enum ('ADMIN','USER'),
        primary key (id)
    );

    -- 【中文：为 memory_embedding 表创建用户 ID 索引，加速按用户查询记忆向量】
    create index idx_memembed_user 
       on memory_embedding (user_id);

    -- 【中文：为 memory_embedding 表创建来源类型+来源 ID 复合索引，支持按来源快速检索】
    create index idx_memembed_source 
       on memory_embedding (source_type, source_id);

    -- 【中文：ai_review → task_submission 外键，关联审核记录与任务提交】
    alter table if exists ai_review 
       add constraint FKhafnxrj0blkujb7fxygl5kwxo 
       foreign key (submission_id) 
       references task_submission;

    -- 【中文：appeal → task_submission 外键，关联申诉与被申诉的任务提交】
    alter table if exists appeal 
       add constraint FK93uiuyjusfxdtu8m9i9ngr0ms 
       foreign key (submission_id) 
       references task_submission;

    -- 【中文：appeal → user_account 外键，关联申诉与发起申诉的用户】
    alter table if exists appeal 
       add constraint FKr8jrmvdb7gob0fn7ll3ewrfhk 
       foreign key (user_id) 
       references user_account;

    -- 【中文：exp_log → task_submission 外键，关联经验值变动与任务提交】
    alter table if exists exp_log 
       add constraint FKc3tu70gco9vcjrn3oydxcgook 
       foreign key (submission_id) 
       references task_submission;

    -- 【中文：exp_log → study_task 外键，关联经验值变动与学习任务】
    alter table if exists exp_log 
       add constraint FK7ifceqhap01b28x9ekvb7d6sx 
       foreign key (task_id) 
       references study_task;

    -- 【中文：exp_log → user_account 外键，关联经验值变动与用户】
    alter table if exists exp_log 
       add constraint FKrf6u552i4st9rpk1qatxm64xp 
       foreign key (user_id) 
       references user_account;

    -- 【中文：focus_session → user_account 外键，关联专注会话与用户】
    alter table if exists focus_session 
       add constraint FKsct087mhopxd640aer3qkeh3c 
       foreign key (user_id) 
       references user_account;

    -- 【中文：goal → user_account 外键，关联目标与用户】
    alter table if exists goal 
       add constraint FKak05c4h8h5952vcr651enxkxb 
       foreign key (user_id) 
       references user_account;

    -- 【中文：memory_embedding → user_account 外键，关联记忆向量与用户】
    alter table if exists memory_embedding 
       add constraint FKdm8lj4pj2jm0fa3w2iwypdji1 
       foreign key (user_id) 
       references user_account;

    -- 【中文：moderation_log → user_account 外键，关联内容审核日志与用户】
    alter table if exists moderation_log 
       add constraint FK20gs9ihbb5ux9wd9wcojotkt3 
       foreign key (user_id) 
       references user_account;

    -- 【中文：pet → user_account 外键，关联宠物与用户】
    alter table if exists pet 
       add constraint FK75fbgnodurg7yfy14puj12xqy 
       foreign key (user_id) 
       references user_account;

    -- 【中文：planning_session → goal 外键，关联规划会话与目标】
    alter table if exists planning_session 
       add constraint FKhxj4xurfslc5d0evnv3yj65cm 
       foreign key (goal_id) 
       references goal;

    -- 【中文：planning_session → user_account 外键，关联规划会话与用户】
    alter table if exists planning_session 
       add constraint FKj5r9nl43d9xt7nwk2f4oern33 
       foreign key (user_id) 
       references user_account;

    -- 【中文：session_turn → planning_session 外键，关联会话轮次与规划会话】
    alter table if exists session_turn 
       add constraint FKsm2pky0l2hak6rbwyd5um8okj 
       foreign key (session_id) 
       references planning_session;

    -- 【中文：study_record → study_task 外键，关联学习记录与任务】
    alter table if exists study_record 
       add constraint FKb1jwugbqg81x71fr1gkbx2xbx 
       foreign key (task_id) 
       references study_task;

    -- 【中文：study_record → user_account 外键，关联学习记录与用户】
    alter table if exists study_record 
       add constraint FKh1kd3ddos11pxqh27c28q3m53 
       foreign key (user_id) 
       references user_account;

    -- 【中文：study_task → user_account 外键，关联学习任务与用户】
    alter table if exists study_task 
       add constraint FK3gprvg263sj98psa7bemq5ccd 
       foreign key (user_id) 
       references user_account;

    -- 【中文：task_submission → study_task 外键，关联任务提交与学习任务】
    alter table if exists task_submission 
       add constraint FKsolb3qj4vm2ehhv2r3g94aoyr 
       foreign key (task_id) 
       references study_task;

    -- 【中文：task_submission → user_account 外键，关联任务提交与用户】
    alter table if exists task_submission 
       add constraint FKehgrqqwjc8970ov6s66nhutc6 
       foreign key (user_id) 
       references user_account;
