-- 【中文：创建 refresh_token 表（H2 版本）—— 实现双令牌认证方案，结构与 MySQL 版本一致。】
-- Refresh tokens for the dual-token auth scheme. Access JWTs stay short (~1h);
-- refresh tokens live for 30d, are stored as SHA-256 hash (so a DB leak doesn't
-- yield usable tokens), and can be revoked server-side (logout / logout-all).
CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 【中文：主键，H2 自增 ID】
    user_id BIGINT NOT NULL,                                  -- 【中文：关联用户 ID】
    token_hash VARCHAR(64) NOT NULL,                          -- 【中文：refresh token 的 SHA-256 哈希值】
    expires_at TIMESTAMP(6) NOT NULL,                         -- 【中文：令牌过期时间】
    revoked_at TIMESTAMP(6),                                  -- 【中文：令牌撤销时间，为空表示有效】
    created_at TIMESTAMP(6) NOT NULL,                         -- 【中文：令牌创建时间】
    last_used_at TIMESTAMP(6),                                -- 【中文：令牌最后使用时间】
    user_agent VARCHAR(255),                                  -- 【中文：客户端 User-Agent】
    ip VARCHAR(64),                                           -- 【中文：客户端 IP 地址】
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES user_account(id)  -- 【中文：外键关联用户表】
);
-- 【中文：令牌哈希唯一索引，用于快速查找和防重复】
CREATE UNIQUE INDEX idx_refresh_token_hash ON refresh_token(token_hash);
-- 【中文：用户 ID 索引，用于查询用户的所有令牌】
CREATE INDEX idx_refresh_token_user ON refresh_token(user_id);
