-- 【中文：创建 notification 表（H2 版本）—— 用户通知系统，结构与 MySQL 版本一致。】
-- User-facing notifications. Created in-process by services (AI review done,
-- appeal reviewed, content blocked, etc.). Read state is per-row so a user can
-- mark individual items read or hit "mark all read".
CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 【中文：主键，H2 自增 ID】
    user_id BIGINT NOT NULL,                                  -- 【中文：接收通知的用户 ID】
    type VARCHAR(32) NOT NULL,                                -- 【中文：通知类型】
    title VARCHAR(200) NOT NULL,                              -- 【中文：通知标题】
    body VARCHAR(1000),                                       -- 【中文：通知正文】
    ref_type VARCHAR(32),                                     -- 【中文：关联实体类型】
    ref_id BIGINT,                                            -- 【中文：关联实体 ID】
    read_at TIMESTAMP(6),                                     -- 【中文：已读时间，为空表示未读】
    created_at TIMESTAMP(6) NOT NULL,                         -- 【中文：通知创建时间】
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES user_account(id)  -- 【中文：外键关联用户表】
);
-- 【中文：创建用户 ID + 已读时间复合索引，加速"查询我的未读通知"这一高频查询】
-- Hot index for the "show me my unread" query.
CREATE INDEX idx_notification_user_read ON notification(user_id, read_at);
-- 【中文：用户 + 创建时间复合索引，加速按时间排序的通知列表查询】
CREATE INDEX idx_notification_user_created ON notification(user_id, created_at);
