-- 【中文：创建 audit_log 表（H2 版本）—— 通用安全审计日志，结构与 MySQL 版本一致。】
-- Generic audit log. Captures user-facing security events (login success/failure,
-- logout, password change, refresh-token replay) and admin lifecycle actions
-- (user creation, role updates). Separate from admin_audit_log (review queue
-- actions) and moderation_log (content filter hits) on purpose — those two tables
-- have richer per-domain schemas and are kept independent.
CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 【中文：主键，H2 自增 ID】
    actor_user_id BIGINT,                                     -- 【中文：操作者用户 ID】
    actor_username VARCHAR(64),                               -- 【中文：操作者用户名】
    actor_role VARCHAR(32),                                   -- 【中文：操作者角色】
    action VARCHAR(64) NOT NULL,                              -- 【中文：操作类型】
    target_type VARCHAR(32),                                  -- 【中文：目标实体类型】
    target_id BIGINT,                                         -- 【中文：目标实体 ID】
    ip VARCHAR(64),                                           -- 【中文：操作者 IP 地址】
    user_agent VARCHAR(255),                                  -- 【中文：操作者 User-Agent】
    success BOOLEAN NOT NULL,                                 -- 【中文：操作是否成功】
    details TEXT,                                             -- 【中文：额外详情】
    created_at TIMESTAMP(6) NOT NULL                          -- 【中文：操作时间】
);
-- 【中文：操作者+时间复合索引，支持查询某用户的操作历史】
CREATE INDEX idx_audit_log_actor_created ON audit_log(actor_user_id, created_at);
-- 【中文：操作类型+时间复合索引，支持按事件类型筛选】
CREATE INDEX idx_audit_log_action_created ON audit_log(action, created_at);
-- 【中文：目标类型+ID 复合索引，支持查看某对象的操作记录】
CREATE INDEX idx_audit_log_target ON audit_log(target_type, target_id);
