-- 【中文：创建 course_entry 表（H2 版本）—— 存储用户从教务系统导入的课程表条目。
--   数据来源：用户粘贴教务系统课表 HTML，经大模型解析为结构化字段后写入。
--   一个用户多条记录，按 (semester, day_of_week, start_section) 组织成周课表。
--   结构与 mysql 版本保持一致。】
-- Course-timetable entries imported from the school academic system (pasted HTML -> LLM -> JSON).
CREATE TABLE course_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 【中文：主键，H2 自增 ID】
    user_id BIGINT NOT NULL,                                  -- 【中文：关联用户 ID】
    course_name VARCHAR(200) NOT NULL,                        -- 【中文：课程名称】
    teacher VARCHAR(100),                                     -- 【中文：任课教师】
    location VARCHAR(120),                                    -- 【中文：上课地点/教室】
    day_of_week INT NOT NULL,                                 -- 【中文：星期几 1-7，周一=1】
    start_section INT,                                        -- 【中文：起始节次】
    end_section INT,                                          -- 【中文：结束节次】
    start_time VARCHAR(8),                                    -- 【中文：上课开始时间 HH:mm】
    end_time VARCHAR(8),                                      -- 【中文：上课结束时间 HH:mm】
    weeks VARCHAR(60),                                        -- 【中文：开课周次原文，如 1-16】
    week_parity VARCHAR(8),                                   -- 【中文：单双周 ALL/ODD/EVEN】
    semester VARCHAR(40),                                     -- 【中文：学期标识，如 2025-2026-2】
    created_at TIMESTAMP(6) NOT NULL,                         -- 【中文：创建时间】
    CONSTRAINT fk_course_entry_user FOREIGN KEY (user_id) REFERENCES user_account(id)  -- 【中文：外键关联用户表】
);
-- 【中文：用户 ID 索引，查询某用户课表时使用】
CREATE INDEX idx_course_entry_user ON course_entry(user_id);
-- 【中文：用户 + 学期复合索引，按学期筛选课表时使用】
CREATE INDEX idx_course_entry_user_sem ON course_entry(user_id, semester);
