-- 【AI 拆解对话（Gemini 式重构）新表：分类 / 对话 / 消息】H2（MySQL 兼容模式）版
-- 与 mysql/V10 对应。旧的 goal + planning_session 表暂留不动。

create table chat_category (
    id bigint generated by default as identity,
    user_id bigint not null,
    name varchar(60) not null,
    sort_order integer not null,
    created_at timestamp(6),
    primary key (id)
);

create table chat_conversation (
    id bigint generated by default as identity,
    user_id bigint not null,
    category_id bigint,
    title varchar(200) not null,
    pending_plan_json TEXT,
    running_summary TEXT,
    summarized_up_to_idx integer not null,
    turn_count integer not null,
    created_at timestamp(6),
    last_activity_at timestamp(6),
    primary key (id)
);

create table chat_message (
    id bigint generated by default as identity,
    conversation_id bigint not null,
    idx integer not null,
    role enum ('ASSISTANT','USER') not null,
    content MEDIUMTEXT,
    created_at timestamp(6),
    primary key (id)
);

alter table if exists chat_category
    add constraint fk_chat_category_user foreign key (user_id) references user_account (id);
alter table if exists chat_conversation
    add constraint fk_chat_conv_user foreign key (user_id) references user_account (id);
alter table if exists chat_conversation
    add constraint fk_chat_conv_category foreign key (category_id) references chat_category (id);
alter table if exists chat_message
    add constraint fk_chat_msg_conv foreign key (conversation_id) references chat_conversation (id);

create index idx_chat_category_user on chat_category (user_id);
create index idx_chat_conv_user on chat_conversation (user_id);
create index idx_chat_conv_category on chat_conversation (category_id);
create index idx_chat_msg_conv on chat_message (conversation_id);
